"""add language to posts

Revision ID: 379db6b8bd0e
Revises: cf6fc60fa0d5
Create Date: 2022-05-15 14:24:55.398321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379db6b8bd0e'
down_revision = 'cf6fc60fa0d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
